server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.StringSerializer

      properties:
        enable.idempotence: true
        acks: all
        retries: 3

security:
  jwt:
    secret: AbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcd=AbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcd=AbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcd=

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}